# username/repository
id: UTCNFans/QuarkChat
# name of the software
name: QuarkChat Project
# current version of the software
version: 0.11 (Stable)
# licence of the software
license: GNU General Public License v3.0
licenseUrl: https://www.gnu.org/licenses/gpl-3.0.html
# extension of the favicon, blank to disable
favicon: png

# download button
# if download.popup is true, the download button will open a popup with several download options
# otherwise it will simply open download.url and other options are ignored
# if download.popup is true, any option is optional
# download.cdn.img is optional
download:
  popup: true
  url: https://github.com/UTCNFans/QuarkChat/raw/master/QuarkChat.jar
  cdn:
    url: null
    img: null
    name: cdnjs

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub UTCNFans
    url: https://github.com/UTCNFans

# list if additional links on the footer
footerLinks:
  - title: GitHub QuarkChat
    url: https://github.com/UTCNFans/QuarkChat
  - title: Issues
    url: https://github.com/UTCNFans/QuarkChat/issues

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: UTCNFans
  repo: QuarkChat

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
